version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    target-branch: "samlauth-api-docker"  # 開発突端のブランチを指定
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
      - "backend"
    groups:
      backend-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "samlauth-api-docker"  # 開発突端のブランチを指定
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "samlauth-api-docker"  # 開発突端のブランチを指定
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    target-branch: "samlauth-api-docker"  # 開発突端のブランチを指定
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "samlauth-api-docker"  # 開発突端のブランチを指定
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "ci"
